# Generated by Django 3.2.10 on 2021-12-25 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was firstly created. Do not modify.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated each time the record is saved.')),
                ('editedrecord', models.BooleanField(default=False, help_text='Tick to indicate that this record has been finalized', verbose_name='edited record?')),
                ('review', models.BooleanField(default=False, help_text='Tick to indicate that this record is under review by the editorial team', verbose_name='review')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal_notes')),
                ('isprivate', models.BooleanField(blank=True, default=False, verbose_name='is private')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_language', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_language', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Language',
            },
        ),
        migrations.CreateModel(
            name='TextExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was firstly created. Do not modify.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated each time the record is saved.')),
                ('editedrecord', models.BooleanField(default=False, help_text='Tick to indicate that this record has been finalized', verbose_name='edited record?')),
                ('review', models.BooleanField(default=False, help_text='Tick to indicate that this record is under review by the editorial team', verbose_name='review')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal_notes')),
                ('isprivate', models.BooleanField(blank=True, default=False, verbose_name='is private')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='author')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('pubyear', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_textexpression', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tractatusapp.language', verbose_name='language')),
                ('updated_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_textexpression', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Text Expression',
            },
        ),
        migrations.CreateModel(
            name='TextFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was firstly created. Do not modify.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated each time the record is saved.')),
                ('editedrecord', models.BooleanField(default=False, help_text='Tick to indicate that this record has been finalized', verbose_name='edited record?')),
                ('review', models.BooleanField(default=False, help_text='Tick to indicate that this record is under review by the editorial team', verbose_name='review')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal_notes')),
                ('isprivate', models.BooleanField(blank=True, default=False, verbose_name='is private')),
                ('contents', models.TextField(blank=True, verbose_name='contents')),
                ('created_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_textfragment', to=settings.AUTH_USER_MODEL)),
                ('in_expression', models.ManyToManyField(blank=True, to='tractatusapp.TextExpression', verbose_name='The Expression(s) this fragment belongs to')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tractatusapp.language', verbose_name='language')),
                ('updated_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_textfragment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Text Fragments',
            },
        ),
        migrations.CreateModel(
            name='TextUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was firstly created. Do not modify.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated each time the record is saved.')),
                ('editedrecord', models.BooleanField(default=False, help_text='Tick to indicate that this record has been finalized', verbose_name='edited record?')),
                ('review', models.BooleanField(default=False, help_text='Tick to indicate that this record is under review by the editorial team', verbose_name='review')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal_notes')),
                ('isprivate', models.BooleanField(blank=True, default=False, verbose_name='is private')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_textunittype', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_textunittype', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TextUnitType',
            },
        ),
        migrations.CreateModel(
            name='TextUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was firstly created. Do not modify.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated each time the record is saved.')),
                ('editedrecord', models.BooleanField(default=False, help_text='Tick to indicate that this record has been finalized', verbose_name='edited record?')),
                ('review', models.BooleanField(default=False, help_text='Tick to indicate that this record is under review by the editorial team', verbose_name='review')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal_notes')),
                ('isprivate', models.BooleanField(blank=True, default=False, verbose_name='is private')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_textunit', to=settings.AUTH_USER_MODEL)),
                ('hascontents', models.ManyToManyField(blank=True, to='tractatusapp.TextFragment')),
                ('hastype', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='tractatusapp.textunittype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tractatusapp.textunit', verbose_name='parent')),
                ('updated_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_textunit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TextUnits',
                'ordering': ['tree_id', 'name'],
            },
        ),
    ]
