# Generated by Django 3.2.25 on 2026-08-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tractatusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this record was firstly created. Do not modify.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated each time the record is saved.')),
                ('editedrecord', models.BooleanField(default=False, help_text='Tick to indicate that this record has been finalized', verbose_name='edited record?')),
                ('review', models.BooleanField(default=False, help_text='Tick to indicate that this record is under review by the editorial team', verbose_name='review')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal_notes')),
                ('isprivate', models.BooleanField(blank=True, default=False, verbose_name='is private')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('external_id', models.SlugField(help_text='lower-cased OCML instance name, for idempotent re-import', max_length=200, unique=True, verbose_name='OCML identifier')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('defined_by_view', models.CharField(blank=True, max_length=200, verbose_name='defined by view')),
                ('created_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_topic', to=settings.AUTH_USER_MODEL)),
                ('textunits', models.ManyToManyField(blank=True, related_name='topics', to='tractatusapp.TextUnit')),
                ('updated_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_topic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
