;; here all the interepretations of the concepts of the tractatus


(in-package ocml)



;; ++++
;;; new interpretations  sept 07
;; ++++


(def-instance   -CONCEPT-INTERPRETATION-G1571638    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  INEFFABLE-BY-WITTGENSTEIN) 
(INTERPRETS  SILENCE-CONCEPT-G652391) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1544145    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  WORLD-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  INEFFABLE-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  ESSENCE-CONCEPT-G470448) 
(INTERPRETS  ESSENCE-OF-THE-WORLD-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1516652    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  SILENCE-CONCEPT-G652391) 
(HAS-RELATED-CONCEPT  MYSTICAL-BY-WITTGENSTEIN   ESSENCE-OF-THE-WORLD-BY-WITTGENSTEIN) 
(INTERPRETS  INEFFABLE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1489159    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  INEFFABLE-BY-WITTGENSTEIN   LIMIT-WORLD-CONCEPT-G275293   ) 
(INTERPRETS  MYSTICAL-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1461666    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  DEATH-BY-WITTGENSTEIN   ETERNAL-LIFE-CONCEPT-G642969) 
(INTERPRETS  SOUL-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1434157    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  LIFE-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  SOUL-BY-WITTGENSTEIN) 
(INTERPRETS  ETERNAL-LIFE-CONCEPT-G642969) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1406628    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  LIFE-BY-WITTGENSTEIN  WORLD-BY-WITTGENSTEIN   EXPERIENCE-BY-WITTGENSTEIN    SOUL-BY-WITTGENSTEIN    ) 
(INTERPRETS  DEATH-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1379135    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  LIMIT-LIFE-CONCEPT-G633547) 
(HAS-RELATED-CONCEPT  ETERNAL-LIFE-CONCEPT-G642969) 
(HAS-OPPOSITE-CONCEPT  DEATH-BY-WITTGENSTEIN) 
(INTERPRETS  LIFE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  LIFE-VISUAL-FIELD-METAPHOR-G384993) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1351611    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  VALUE-BY-WITTGENSTEIN   PROP-AESTHETICS-CONCEPT-G624125) 
(IS-SPECIALIZATION-OF  PROP-NONSENSE-CONCEPT-G223866) 
(INTERPRETS  PROP-ETHICS-CONCEPT-G614703) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1324118    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  VALUE-BY-WITTGENSTEIN  PROP-ETHICS-CONCEPT-G614703) 
(IS-SPECIALIZATION-OF  PROP-NONSENSE-CONCEPT-G223866) 
(INTERPRETS  PROP-AESTHETICS-CONCEPT-G624125) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1296625    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  WORLD-BY-WITTGENSTEIN) 
(INTERPRETS  VALUE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  ETHICS-BY-WITTGENSTEIN  AESTHETICS) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1269132    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  WILL-BY-WITTGENSTEIN   WORLD-BY-WITTGENSTEIN   ) 
(INTERPRETS  ACTION-CONCEPT-G605281) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1241639    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  WORLD-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  NECESSARY-CONCEPT-G595859) 
(INTERPRETS  ACCIDENTAL-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G1214138    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  ACCIDENTAL-BY-WITTGENSTEIN   ACTION-CONCEPT-G605281   ) 
(HAS-OPPOSITE-CONCEPT  WILL-BY-WITTGENSTEIN   VALUE-BY-WITTGENSTEIN DEATH-BY-WITTGENSTEIN  ) 
(INTERPRETS  WORLD-BY-WITTGENSTEIN) 
(CONTRASTS-WITH  LOGIC) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1187609    CONCEPT-INTERPRETATION 
((INTERPRETS  GOD-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  FATE-SCIENCE-ANALOGY-G384519) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1161080    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LIMIT-WILL-CONCEPT-G282960  ACTION-CONCEPT-G605281) 
(HAS-OPPOSITE-CONCEPT  WORLD-BY-WITTGENSTEIN) 
(INTERPRETS  WILL-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1134535    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  A-PRIORI-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  PROP-OF-SCIENCE-CONCEPT-G558368) 
(IS-EQUIVALENT-TO  LAW-OF-NATURE-BY-WITTGENSTEIN) 
(INTERPRETS  FORM-PROP-SCIENCE-CONCEPT-G567160) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1108006    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LAW-OF-NATURE-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  FORM-PROP-SCIENCE-CONCEPT-G567160) 
(IS-SPECIALIZATION-OF  PROP-WITH-A-SENSE-CONCEPT-G360985) 
(INTERPRETS  PROP-OF-SCIENCE-CONCEPT-G558368) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1081477    CONCEPT-INTERPRETATION 
((IS-SPECIALIZATION-OF  LAW-OF-NATURE-BY-WITTGENSTEIN) 
(INTERPRETS  LAW-OF-CAUSALITY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1054948    CONCEPT-INTERPRETATION 
((IS-SPECIALIZATION-OF  LAW-OF-NATURE-BY-WITTGENSTEIN) 
(INTERPRETS  LAW-OF-INDUCTION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1028361    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LAWS-OF-LOGIC-CONCEPT-G549576) 
(INTERPRETS  NECESSARY-CONCEPT-G595859) 
(IS-RELATED-TO-IDEA  LOGIC) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G1001832    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  A-PRIORI-BY-WITTGENSTEIN  NECESSARY-CONCEPT-G595859   ) 
(HAS-OPPOSITE-CONCEPT  LAW-OF-NATURE-BY-WITTGENSTEIN) 
(INTERPRETS  LAWS-OF-LOGIC-CONCEPT-G549576) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G975261    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  EXPERIENCE-BY-WITTGENSTEIN   PROP-OF-SCIENCE-CONCEPT-G558368   ) 
(HAS-OPPOSITE-CONCEPT  LAWS-OF-LOGIC-CONCEPT-G549576) 
(IS-EQUIVALENT-TO    FORM-PROP-SCIENCE-CONCEPT-G567160)
(IS-GENERALIZATION-OF  LAW-OF-INDUCTION-BY-WITTGENSTEIN   LAW-OF-CAUSALITY-BY-WITTGENSTEIN    ) 
(INTERPRETS  LAW-OF-NATURE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  MESH-METAPHOR-G384045    FATE-SCIENCE-ANALOGY-G384519    ) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G948724    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LOGICAL-ORDER-CONCEPT-G540784) 
(INTERPRETS  ORDINARY-LANGUAGE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G923648    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  ORDINARY-LANGUAGE-BY-WITTGENSTEIN) 
(INTERPRETS  LOGICAL-ORDER-CONCEPT-G540784) 
(IS-RELATED-TO-IDEA  LOGIC) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G898572    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  EQUATION-CONCEPT-G514408) 
(INTERPRETS  INFERENCE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G873454    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  EQUATION-CONCEPT-G514408) 
(INTERPRETS  IDENTITY-SIGN-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G848336    CONCEPT-INTERPRETATION 
((IS-EQUIVALENT-TO  EQUATION-CONCEPT-G514408   PROPOSITIONS-MATHEMATICS-CONCEPT-G505616   ) 
(INTERPRETS  ABSTRACTION-CONCEPT-G523200) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G823260    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  INFERENCE-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  IDENTITY-SIGN-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  PROPOSITIONS-MATHEMATICS-CONCEPT-G505616   ABSTRACTION-CONCEPT-G523200   ) 
(INTERPRETS  EQUATION-CONCEPT-G514408) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G798184    CONCEPT-INTERPRETATION 
((IS-EQUIVALENT-TO  EQUATION-CONCEPT-G514408   ABSTRACTION-CONCEPT-G523200   ) 
(IS-SPECIALIZATION-OF  PROP-NONSENSE-CONCEPT-G223866) 
(INTERPRETS  PROPOSITIONS-MATHEMATICS-CONCEPT-G505616) 
(IS-RELATED-TO-IDEA  MATHEMATICS) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G773108    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  TRUTH-VALUE-PROP-CONCEPT-G231083) 
(HAS-RELATED-CONCEPT  INFERENCE-BY-WITTGENSTEIN) 
(INTERPRETS  FOLLOW-CONCEPT-G369105) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G748028    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  PROP-OF-LOGIC-CONCEPT-G394004) 
(HAS-RELATED-CONCEPT  LOGICAL-PROOF-CONCEPT-G496824) 
(INTERPRETS  FORM-LOGICAL-PROOF-CONCEPT-G531992) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G722952    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  TAUTOLOGY-BY-WITTGENSTEIN  PROP-OF-LOGIC-CONCEPT-G394004    ) 
(INTERPRETS  LOGICAL-PROOF-CONCEPT-G496824) 
(IS-RELATED-TO-IDEA  LOGIC) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G697876    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  FORM-LOGICAL-PROOF-CONCEPT-G531992) 
(HAS-OPPOSITE-CONCEPT  LOGICAL-PROOF-CONCEPT-G496824) 
(IS-RELATED-TO-IDEA  SCAFFOLDING-METAPHOR-G383571)
(INTERPRETS  PROP-OF-LOGIC-CONCEPT-G394004) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G672776    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  OPERATION-CONCEPT-G377410) 
(INTERPRETS  NUMBER-CONCEPT-G488032) 
(IS-RELATED-TO-IDEA  MATHEMATICS) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G647652    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  APPLICATION-OPERATION-CONCEPT-G479240   NEGATION-OPERATION-CONCEPT-G385707   ) 
(HAS-OPPOSITE-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  COMPLEX-PROPOSITION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G622576    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  COMPLEX-PROPOSITION-BY-WITTGENSTEIN) 
(REQUIRES-CONCEPT  OPERATION-CONCEPT-G377410) 
(INTERPRETS  APPLICATION-OPERATION-CONCEPT-G479240) 
(IS-RELATED-TO-IDEA  MATHEMATICS) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G597500    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  NEGATION-OPERATION-CONCEPT-G385707) 
(IS-EQUIVALENT-TO  ESSENCE-PROPOSITION-CONCEPT-G402301) 
(INTERPRETS  GENERAL-PROPOSITIONAL-FORM-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G572416    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN) 
(INTERPRETS  HUMAN-BODY-CONCEPT-G453036) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G548599    CONCEPT-INTERPRETATION 
((IS-EQUIVALENT-TO  METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN) 
(INTERPRETS  PHILOSOPHICAL-SELF-CONCEPT-G461648) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G524782    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  WORLD-BY-WITTGENSTEIN   LIMIT-WORLD-CONCEPT-G275293  INEXPRESSIBLE-BY-WITTGENSTEIN ) 
(HAS-OPPOSITE-CONCEPT  SOUL-BY-WITTGENSTEIN   HUMAN-BODY-CONCEPT-G453036   ) 
(IS-EQUIVALENT-TO  PHILOSOPHICAL-SELF-CONCEPT-G461648) 
(INTERPRETS  METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  VISUAL-FIELD-ANALOGY-G381201) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G500965    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  FACT-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  LIMIT-WORLD-CONCEPT-G275293   METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN   ) 
(INTERPRETS  WORLD-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G477099    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  LIMIT-WORLD-CONCEPT-G275293) 
(REQUIRES-CONCEPT  FACT-BY-WITTGENSTEIN) 
(INTERPRETS  TOTALITY-OF-FACTS-CONCEPT-G310086) 
(CARRIED-OUT-BY  michele-pasin)
))

(def-instance   -CONCEPT-INTERPRETATION-G453282    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN) 
(REQUIRES-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  TOTALITY-ELEM-PROP-CONCEPT-G444424) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G429465    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  SHOWING-CONCEPT-G109201) 
(HAS-RELATED-CONCEPT  LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN   LIMIT-WORLD-CONCEPT-G275293  ) 
(INTERPRETS  INEXPRESSIBLE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G405648    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  EXPERIENCE-BY-WITTGENSTEIN) 
(INTERPRETS  LOGICAL-EXPERIENCE-CONCEPT-G435812) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G381831    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  A-POSTERIORI-BY-WITTGENSTEIN  LAW-OF-NATURE-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  LOGICAL-EXPERIENCE-CONCEPT-G435812   DEATH-BY-WITTGENSTEIN) 
(INTERPRETS  EXPERIENCE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G358014    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  KNOWING-CONCEPT-G349594   LAWS-OF-LOGIC-CONCEPT-G549576) 
(HAS-OPPOSITE-CONCEPT  A-POSTERIORI-BY-WITTGENSTEIN) 
(INTERPRETS  A-PRIORI-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G334197    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  PSYCHOLOGICAL-SUBJECT-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROP-NONSENSE-CONCEPT-G223866) 
(INTERPRETS  PROPOSITIONAL-ATTITUDE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G310380    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  PROPOSITIONAL-ATTITUDE-BY-WITTGENSTEIN   METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN   ) 
(HAS-OPPOSITE-CONCEPT  THOUGHT-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  SOUL-BY-WITTGENSTEIN) 
(INTERPRETS  PSYCHOLOGICAL-SUBJECT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G286563    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  PSYCHOLOGICAL-SUBJECT-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PICTURE-BY-WITTGENSTEIN) 
(INTERPRETS  THOUGHT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G262738    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  OUTER-LIMIT-LANGUAGE-CONCEPT-G418895) 
(IS-EQUIVALENT-TO  TAUTOLOGY-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN) 
(INTERPRETS  INNER-LIMIT-LANGUAGE-CONCEPT-G427192) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G239495    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT INNER-LIMIT-LANGUAGE-CONCEPT-G427192)
(IS-EQUIVALENT-TO  CONTRADICTION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN) 
(INTERPRETS  OUTER-LIMIT-LANGUAGE-CONCEPT-G418895) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G216252    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  IDENTITY-SIGN-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  VARIABLE-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  SIGN-BY-WITTGENSTEIN) 
(INTERPRETS  GENERALITY-SIGN-CONCEPT-G410598) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G193009    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  GENERALITY-SIGN-CONCEPT-G410598) 
(IS-SPECIALIZATION-OF  SIGN-BY-WITTGENSTEIN) 
(INTERPRETS  IDENTITY-SIGN-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G169766    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LAWS-OF-LOGIC-CONCEPT-G549576) 
(HAS-OPPOSITE-CONCEPT  LAWS-INFERENCE-CONCEPT-G353411) 
(INTERPRETS  ROLE-OF-LOGIC-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G146523    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  PROPOSITION-BY-WITTGENSTEIN    NEGATION-OPERATION-CONCEPT-G385707    ) 
(IS-EQUIVALENT-TO  GENERAL-PROPOSITIONAL-FORM-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  ESSENCE-CONCEPT-G470448) 
(INTERPRETS  ESSENCE-PROPOSITION-CONCEPT-G402301) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G123272    CONCEPT-INTERPRETATION 
((IS-GENERALIZATION-OF  TAUTOLOGY-BY-WITTGENSTEIN   CONTRADICTION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROP-LACK-SENSE-CONCEPT-G216649) 
(INTERPRETS  PROP-OF-LOGIC-CONCEPT-G394004) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G100510    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  ESSENCE-PROPOSITION-CONCEPT-G402301   GENERAL-PROPOSITIONAL-FORM-BY-WITTGENSTEIN    ) 
(IS-SPECIALIZATION-OF  OPERATION-CONCEPT-G377410) 
(INTERPRETS  NEGATION-OPERATION-CONCEPT-G385707) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G77748    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  TRUTH-FUNCTION-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  OPERATION-CONCEPT-G377410)
(INTERPRETS  TRUTH-OPERATION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G54986    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  APPLICATION-OPERATION-CONCEPT-G479240) 
(HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  TRUTH-OPERATION-BY-WITTGENSTEIN   NEGATION-OPERATION-CONCEPT-G385707   ) 
(INTERPRETS  OPERATION-CONCEPT-G377410) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G32224    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  OPERATION-CONCEPT-G377410) 
(IS-EQUIVALENT-TO  LOGICAL-OBJECT-BY-WITTGENSTEIN) 
(INTERPRETS  LOGICAL-CONSTANT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

;;...

(def-instance   -CONCEPT-INTERPRETATION-G553083    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  LAWS-INFERENCE-CONCEPT-G353411) 
(INTERPRETS  PROBABILITY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G532928    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LOGICAL-PROOF-CONCEPT-G496824) 
(HAS-OPPOSITE-CONCEPT  CONTRADICTION-BY-WITTGENSTEIN   TRUTH-VALUE-PROP-CONCEPT-G231083   ) 
(IS-SPECIALIZATION-OF  PROP-OF-LOGIC-CONCEPT-G394004   PROP-LACK-SENSE-CONCEPT-G216649    INNER-LIMIT-LANGUAGE-CONCEPT-G427192   ) 
(INTERPRETS  TAUTOLOGY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G512773    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  TAUTOLOGY-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROP-OF-LOGIC-CONCEPT-G394004   PROP-LACK-SENSE-CONCEPT-G216649   OUTER-LIMIT-LANGUAGE-CONCEPT-G418895      ) 
(INTERPRETS  CONTRADICTION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G492618    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  LAWS-INFERENCE-CONCEPT-G353411) 
(HAS-OPPOSITE-CONCEPT  INFERENCE-BY-WITTGENSTEIN) 
(INTERPRETS  FUTURE-PREDICTIONS-CONCEPT-G361258) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G472463    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  LAWS-INFERENCE-CONCEPT-G353411    FUTURE-PREDICTIONS-CONCEPT-G361258   ) 
(IS-EQUIVALENT-TO  FOLLOW-CONCEPT-G369105) 
(INTERPRETS  INFERENCE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G452308    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  FUTURE-PREDICTIONS-CONCEPT-G361258    PROBABILITY-BY-WITTGENSTEIN    ) 
(HAS-OPPOSITE-CONCEPT  INFERENCE-BY-WITTGENSTEIN  ROLE-OF-LOGIC-BY-WITTGENSTEIN    ) 
(INTERPRETS  LAWS-INFERENCE-CONCEPT-G353411) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G432153    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  PROP-NONSENSE-CONCEPT-G223866    PROP-WITH-A-SENSE-CONCEPT-G360985    ) 
(IS-GENERALIZATION-OF  TAUTOLOGY-BY-WITTGENSTEIN    PROP-OF-LOGIC-CONCEPT-G394004   CONTRADICTION-BY-WITTGENSTEIN     ) 
(IS-SPECIALIZATION-OF  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  PROP-LACK-SENSE-CONCEPT-G216649) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G411998    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  TRUTH-GROUNDS-BY-WITTGENSTEIN   SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN   ) 
(HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  INFERENCE-BY-WITTGENSTEIN) 
(INTERPRETS  FOLLOW-CONCEPT-G369105) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G391843    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPOSITIONAL-SIGN-BY-WITTGENSTEIN) 
(INTERPRETS  TRUTH-COND-TABLE-CONCEPT-G345564) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G371688    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  WORLD-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  TOTALITY-TRUE-PROP-CONCEPT-G245517) 
(INTERPRETS  COMPLETE-DESCR-WORLD-CONCEPT-G337717) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G351533    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  WORLD-BY-WITTGENSTEIN  TOTALITY-OF-TRUE-S-O-A-CONCEPT-G315730) 
(INTERPRETS  TOTALITY-EXISTING-SOA-CONCEPT-G329870) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G331378    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  INDEPENDENCE-CONCEPT-G306329) 
(INTERPRETS  INDEPENDENCE-S-O-A-CONCEPT-G322023) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G311223    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  INDEPENDENCE-CONCEPT-G306329) 
(INTERPRETS  INDEPENDENCE-ELE-PROP-CONCEPT-G314176) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G291068    CONCEPT-INTERPRETATION 
((IS-GENERALIZATION-OF  INDEPENDENCE-ELE-PROP-CONCEPT-G314176    INDEPENDENCE-S-O-A-CONCEPT-G322023  ) 
(INTERPRETS  INDEPENDENCE-CONCEPT-G306329) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G270913    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  FOLLOW-CONCEPT-G369105   INFERENCE-BY-WITTGENSTEIN    ) 
(REQUIRES-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  TRUTH-FUNCTION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  TRUTH-POSSIBILITIES-BY-WITTGENSTEIN) 
(INTERPRETS  TRUTH-GROUNDS-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G250758    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  TRUTH-OPERATION-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  TRUTH-GROUNDS-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  TRUTH-FUNCTION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G230603    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  TOTALITY-ELEM-PROP-CONCEPT-G444424   ) 
(REQUIRES-CONCEPT  NAME-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  TRUTH-POSSIBILITIES-BY-WITTGENSTEIN   INDEPENDENCE-ELE-PROP-CONCEPT-G314176   STATE-OF-AFFAIRS-BY-WITTGENSTEIN   TRUTH-OPERATION-BY-WITTGENSTEIN  LOGICAL-EXPERIENCE-CONCEPT-G435812    ) 
(HAS-OPPOSITE-CONCEPT  COMPLEX-PROPOSITION-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G210448    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  TRUTH-COND-TABLE-CONCEPT-G345564) 
(INTERPRETS  TRUTH-CONDITIONS-CONCEPT-G298482) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G190293    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  TRUTH-GROUNDS-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  TRUTH-POSSIBILITIES-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G170138    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  TRUTH-CONDITIONS-CONCEPT-G298482) 
(REQUIRES-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  TRUTH-POSSIBILITIES-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G149983    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  FORMAL-CONCEPT-BY-WITTGENSTEIN   GENERALITY-SIGN-CONCEPT-G410598   ) 
(INTERPRETS  VARIABLE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G129828    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  FORMAL-CONCEPT-BY-WITTGENSTEIN) 
(INTERPRETS  INEXPRESSIBLE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G109673    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  FORMAL-CONCEPT-BY-WITTGENSTEIN) 
(INTERPRETS  CONCEPT-PROPER-CONCEPT-G290627) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G89518    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  INEXPRESSIBLE-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  CONCEPT-PROPER-CONCEPT-G290627   VARIABLE-BY-WITTGENSTEIN   ) 
(INTERPRETS  FORMAL-CONCEPT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G69363    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LOGICAL-STRUCTURE-CONCEPT-G202215   FORMAL-CONCEPT-BY-WITTGENSTEIN  ) 
(HAS-OPPOSITE-CONCEPT  EXTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(INTERPRETS  FORMAL-PROPERTY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G49208    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  LOGICAL-FORM-BY-WITTGENSTEIN) 
(INTERPRETS  REPRESENTING-RELATION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G29617    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  REALITY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


;;...

(def-instance   -CONCEPT-INTERPRETATION-G755542    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LIFE-BY-WITTGENSTEIN   DEATH-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  LIMIT-CONCEPT-G267626) 
(INTERPRETS  LIMIT-LIFE-CONCEPT-G633547) 
(IS-RELATED-TO-IDEA  LIFE-VISUAL-FIELD-METAPHOR-G384993) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G736341    CONCEPT-INTERPRETATION 
((IS-SPECIALIZATION-OF  LIMIT-CONCEPT-G267626) 
(HAS-RELATED-CONCEPT  WILL-BY-WITTGENSTEIN   )
(INTERPRETS  LIMIT-WILL-CONCEPT-G282960) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G717140    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  MYSTICAL-BY-WITTGENSTEIN   TOTALITY-OF-FACTS-CONCEPT-G310086) 
(HAS-RELATED-CONCEPT  WORLD-BY-WITTGENSTEIN  METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN  SHOWING-CONCEPT-G109201   ) 
(IS-SPECIALIZATION-OF  LIMIT-CONCEPT-G267626) 
(INTERPRETS  LIMIT-WORLD-CONCEPT-G275293) 
(IS-RELATED-TO-IDEA  VISUAL-FIELD-ANALOGY-G381201) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G697939    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  TOTALITY-ELEM-PROP-CONCEPT-G444424) 
(HAS-RELATED-CONCEPT  SHOWING-CONCEPT-G109201  LANGUAGE-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  INNER-LIMIT-LANGUAGE-ONCEPT-G427192    OUTER-LIMIT-LANGUAGE-CONCEPT-G418895C) 
(IS-SPECIALIZATION-OF  LIMIT-CONCEPT-G267626) 
(INTERPRETS  LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G678738    CONCEPT-INTERPRETATION 
((IS-GENERALIZATION-OF  LIMIT-LIFE-CONCEPT-G633547   LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN    LIMIT-WILL-CONCEPT-G282960   LIMIT-WORLD-CONCEPT-G275293) 
(INTERPRETS  LIMIT-CONCEPT-G267626) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G659537    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  ROLE-OF-PHILOSOPHY-BY-WITTGENSTEIN) 
(INTERPRETS  ACTIVITY-CONCEPT-G259951) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G640336    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  SILENCE-CONCEPT-G652391) 
(HAS-RELATED-CONCEPT  ACTIVITY-CONCEPT-G259951   MYSTICAL-BY-WITTGENSTEIN   ) 
(HAS-OPPOSITE-CONCEPT  ROLE-NAT-SCIENCE-CONCEPT-G252734   ROLE-OF-LOGIC-BY-WITTGENSTEIN   ) 
(INTERPRETS  ROLE-OF-PHILOSOPHY-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN   LADDER-METAPHOR-G385467   ) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G621135    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  NATURAL-SCIENCE-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  ROLE-OF-PHILOSOPHY-BY-WITTGENSTEIN) 
(INTERPRETS  ROLE-NAT-SCIENCE-CONCEPT-G252734) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G601934    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  ROLE-NAT-SCIENCE-CONCEPT-G252734  LAW-OF-NATURE-BY-WITTGENSTEIN  PROP-OF-SCIENCE-CONCEPT-G558368    ) 
(IS-EQUIVALENT-TO  TOTALITY-TRUE-PROP-CONCEPT-G245517) 
(INTERPRETS  NATURAL-SCIENCE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G582733    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  TOTALITY-PROP-CONCEPT-G238300) 
(IS-GENERALIZATION-OF  PERFECT-LANGUAGE-BY-WITTGENSTEIN   ORDINARY-LANGUAGE-BY-WITTGENSTEIN   ) 
(INTERPRETS  LANGUAGE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G563524    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  COMPLETE-DESCR-WORLD-CONCEPT-G337717   NATURAL-SCIENCE-BY-WITTGENSTEIN  PROP-OF-SCIENCE-CONCEPT-G558368    ) 
(IS-SPECIALIZATION-OF  TOTALITY-PROP-CONCEPT-G238300) 
(INTERPRETS  TOTALITY-TRUE-PROP-CONCEPT-G245517) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G544513    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  LANGUAGE-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  TOTALITY-TRUE-PROP-CONCEPT-G245517    TOTALITY-ELEM-PROP-CONCEPT-G444424) 
(INTERPRETS  TOTALITY-PROP-CONCEPT-G238300) 
(CARRIED-OUT-BY  michele-pasin) 
))


;; ..

(def-instance   -CONCEPT-INTERPRETATION-G525494    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  PROPOSITION-BY-WITTGENSTEIN    FOLLOW-CONCEPT-G369105    ) 
(HAS-OPPOSITE-CONCEPT  SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN   PROP-OF-LOGIC-CONCEPT-G394004   ) 
(INTERPRETS  TRUTH-VALUE-PROP-CONCEPT-G231083) 
(IS-RELATED-TO-IDEA  TRUE-FALSE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G508288    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  MEANING-NAME-CONCEPT-G161230) 
(HAS-OPPOSITE-CONCEPT  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPERTY-CONCEPT-G34847) 
(INTERPRETS  EXTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G491082    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  FORMAL-CONCEPT-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN   LOGICAL-STRUCTURE-CONCEPT-G202215   ) 
(HAS-OPPOSITE-CONCEPT  EXTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  FORMAL-PROPERTY-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPERTY-CONCEPT-G34847) 
(INTERPRETS  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G473876    CONCEPT-INTERPRETATION 
((IS-GENERALIZATION-OF  LOGICAL-PICTURE-BY-WITTGENSTEIN   PROPOSITION-BY-WITTGENSTEIN   ) 
(INTERPRETS  PICTURE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G456670    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  INTERNAL-PROPERTY-BY-WITTGENSTEIN   FOLLOW-CONCEPT-G369105     ) 
(REQUIRES-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  TRUTH-COND-TABLE-CONCEPT-G345564) 
(HAS-OPPOSITE-CONCEPT  TRUTH-VALUE-PROP-CONCEPT-G231083) 
(IS-SPECIALIZATION-OF  SENSE-BY-WITTGENSTEIN) 
(INTERPRETS  SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G439464    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  NONSENSICAL-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  PROP-LACK-SENSE-CONCEPT-G216649   PROP-WITH-A-SENSE-CONCEPT-G360985  ) 
(IS-EQUIVALENT-TO  PROBLEMS-OF-PHILOSOPHY-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  PROP-AESTHETICS-CONCEPT-G624125   PROP-ETHICS-CONCEPT-G614703   PROPOSITIONAL-ATTITUDE-BY-WITTGENSTEIN   LAW-OF-NATURE-BY-WITTGENSTEIN     ) 
(IS-SPECIALIZATION-OF  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  PROP-NONSENSE-CONCEPT-G223866) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G422258    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  PROBLEMS-OF-PHILOSOPHY-BY-WITTGENSTEIN) 
(INTERPRETS  PHILOSOPHICAL-CONFUSION-CONCEPT-G209432) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G405052    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  ORDINARY-LANGUAGE-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  PHILOSOPHICAL-CONFUSION-CONCEPT-G209432) 
(HAS-OPPOSITE-CONCEPT  ROLE-OF-PHILOSOPHY-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  PROP-NONSENSE-CONCEPT-G223866) 
(INTERPRETS  PROBLEMS-OF-PHILOSOPHY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G387846    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  FORMAL-PROPERTY-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  STRUCTURE-OF-SOA-CONCEPT-G41116  STRUCTURE-PICTURE-CONCEPT-G72109   ) 
(HAS-OPPOSITE-CONCEPT  ORDINARY-LANGUAGE-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  STRUCTURE-BY-WITTGENSTEIN) 
(INTERPRETS  LOGICAL-STRUCTURE-CONCEPT-G202215) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G370591    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  PROBLEMS-OF-PHILOSOPHY-BY-WITTGENSTEIN   PHILOSOPHICAL-CONFUSION-CONCEPT-G209432   ) 
(HAS-OPPOSITE-CONCEPT  LOGICAL-STRUCTURE-CONCEPT-G202215) 
(INTERPRETS  ORDINARY-LANGUAGE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G353385    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  OPERATION-CONCEPT-G377410) 
(IS-EQUIVALENT-TO  LOGICAL-OBJECT-BY-WITTGENSTEIN) 
(INTERPRETS  LOGICAL-CONSTANT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G336179    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  PERFECT-LANGUAGE-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  LANGUAGE-BY-WITTGENSTEIN) 
(INTERPRETS  ORDINARY-LANGUAGE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G318973    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  ORDINARY-LANGUAGE-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  LANGUAGE-BY-WITTGENSTEIN) 
(INTERPRETS  PERFECT-LANGUAGE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G301767    CONCEPT-INTERPRETATION 
((IS-GENERALIZATION-OF  GENERALITY-SIGN-CONCEPT-G410598  PRIMITIVE-SIGN-BY-WITTGENSTEIN  PROPOSITIONAL-SIGN-BY-WITTGENSTEIN   IDENTITY-SIGN-BY-WITTGENSTEIN  LOGICAL-SIGN-BY-WITTGENSTEIN    SIGN-SYMBOL-BY-WITTGENSTEIN    ) 
(INTERPRETS  SIGN-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G284561    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  ELUCIDATION-CONCEPT-G168267) 
(HAS-RELATED-CONCEPT  LOGICAL-FORM-BY-WITTGENSTEIN   MEANING-NAME-CONCEPT-G161230   ) 
(HAS-OPPOSITE-CONCEPT  SAYING-CONCEPT-G103019) 
(INTERPRETS  SHOWING-CONCEPT-G109201) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G267355    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  MEANING-NAME-CONCEPT-G161230) 
(HAS-RELATED-CONCEPT  SHOWING-CONCEPT-G109201) 
(INTERPRETS  ELUCIDATION-CONCEPT-G168267) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G250149    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT   ELUCIDATION-CONCEPT-G168267   ) 
(REQUIRES-CONCEPT  NAME-BY-WITTGENSTEIN  OBJECT-BY-WITTGENSTEIN  ) 
(HAS-RELATED-CONCEPT  SHOWING-CONCEPT-G109201  EXTERNAL-PROPERTY-BY-WITTGENSTEIN   ) 
(INTERPRETS  MEANING-NAME-CONCEPT-G161230) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G232943    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  MEANING-NAME-CONCEPT-G161230  ) 
(REQUIRES-CONCEPT     OBJECT-BY-WITTGENSTEIN    ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN ) 
(HAS-RELATED-CONCEPT  ANALYSIS-OF-A-PROPOSITION-BY-WITTGENSTEIN   PROPOSITION-BY-WITTGENSTEIN ) 
(INTERPRETS  NAME-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G215737    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  NAME-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  ANALYSIS-OF-A-PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  ANALYSIS-OF-A-PROPOSITION-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


;;;

(def-instance   -CONCEPT-INTERPRETATION-G171942    CONCEPT-INTERPRETATION 
((INTERPRETS  FACT-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  RULER-ANALOGY-G382149) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G155694    CONCEPT-INTERPRETATION 
((INTERPRETS  LOGICAL-PICTURE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  RULER-ANALOGY-G382149) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G139446    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  TRUTH-COND-TABLE-CONCEPT-G345564) 
(IS-SPECIALIZATION-OF  SIGN-BY-WITTGENSTEIN) 
(INTERPRETS  PROPOSITIONAL-SIGN-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G123198    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  PROPOSITION-BY-WITTGENSTEIN   REALITY-BY-WITTGENSTEIN   ) 
(INTERPRETS  LOGICAL-FORM-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  RULER-ANALOGY-G382149) 
))

(def-instance   -CONCEPT-INTERPRETATION-G106950    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  ANALYSIS-OF-A-PROPOSITION-BY-WITTGENSTEIN   FOLLOW-CONCEPT-G369105   ) 
(REQUIRES-CONCEPT  THOUGHT-BY-WITTGENSTEIN   LOGICAL-FORM-BY-WITTGENSTEIN  NAME-BY-WITTGENSTEIN   STATE-OF-AFFAIRS-BY-WITTGENSTEIN   REALITY-BY-WITTGENSTEIN   TRUTH-CONDITIONS-CONCEPT-G298482   TRUTH-VALUE-PROP-CONCEPT-G231083 ) 
(HAS-RELATED-CONCEPT  TOTALITY-PROP-CONCEPT-G238300   TOTALITY-TRUE-PROP-CONCEPT-G245517    LOGICAL-STRUCTURE-CONCEPT-G202215  ESSENCE-PROPOSITION-CONCEPT-G402301     ) 
(HAS-OPPOSITE-CONCEPT  PROPOSITIONAL-SIGN-BY-WITTGENSTEIN   ) 
(IS-GENERALIZATION-OF  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN   COMPLEX-PROPOSITION-BY-WITTGENSTEIN  PROP-WITH-A-SENSE-CONCEPT-G360985   PROP-OF-SCIENCE-CONCEPT-G558368   PROP-OF-LOGIC-CONCEPT-G394004   PROP-NONSENSE-CONCEPT-G223866    PROP-LACK-SENSE-CONCEPT-G216649    PROP-ETHICS-CONCEPT-G614703  PROP-AESTHETICS-CONCEPT-G624125   PROPOSITIONAL-ATTITUDE-BY-WITTGENSTEIN       ) 
(IS-SPECIALIZATION-OF  TRUTH-FUNCTION-BY-WITTGENSTEIN) 
(INTERPRETS  PROPOSITION-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  NOTES-METAPHOR-G385433   SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN   ) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G90702    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  THOUGHT-BY-WITTGENSTEIN) 
(INTERPRETS  ILLOGICAL-THOUGHT-CONCEPT-G133929) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G74454    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  PROPOSITION-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  ILLOGICAL-THOUGHT-CONCEPT-G133929) 
(IS-SPECIALIZATION-OF  LOGICAL-PICTURE-BY-WITTGENSTEIN) 
(INTERPRETS  THOUGHT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G58206    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  TRUTH-POSSIBILITIES-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  TRUE-BY-WITTGENSTEIN) 
(INTERPRETS  FALSE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  TRUE-FALSE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G41958    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  TRUTH-POSSIBILITIES-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  FALSE-BY-WITTGENSTEIN) 
(INTERPRETS  TRUE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  TRUE-FALSE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G25710    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  SENSE-PICTURE-CONCEPT-G115383) 
(HAS-RELATED-CONCEPT  REALITY-BY-WITTGENSTEIN) 
(INTERPRETS  COMPARISON-REALITY-CONCEPT-G121565) 
(IS-RELATED-TO-IDEA  TRUE-FALSE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

;;....

(def-instance   -CONCEPT-INTERPRETATION-G927073    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  TRUE-BY-WITTGENSTEIN  ) 
(REQUIRES-CONCEPT  COMPARISON-REALITY-CONCEPT-G121565     POSSIBLE-SITUATION-CONCEPT-G140111   ) 
(HAS-RELATED-CONCEPT  LOGICAL-PICTURE-BY-WITTGENSTEIN   SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN    ) 
(IS-SPECIALIZATION-OF  SENSE-BY-WITTGENSTEIN) 
(INTERPRETS  SENSE-PICTURE-CONCEPT-G115383) 
(IS-RELATED-TO-IDEA  TRUE-FALSE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G911417    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  STRUCTURE-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  LOGICAL-FORM-BY-WITTGENSTEIN   PICTORIAL-FORM-CONCEPT-G78291  FORM-LOGICAL-PROOF-CONCEPT-G531992   FORM-OF-REPRESENTATION-BY-WITTGENSTEIN   FORM-PROP-SCIENCE-CONCEPT-G567160     ) 
(INTERPRETS  FORM-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G895761    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  FORM-BY-WITTGENSTEIN  SILENCE-CONCEPT-G652391) 
(HAS-OPPOSITE-CONCEPT  SAYING-CONCEPT-G103019) 
(INTERPRETS  SHOWING-CONCEPT-G109201) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G880105    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  FACT-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  SHOWING-CONCEPT-G109201) 
(INTERPRETS  SAYING-CONCEPT-G103019) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G864449    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  SENSE-PICTURE-CONCEPT-G115383) 
(HAS-RELATED-CONCEPT  LOGICAL-PICTURE-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  SITUATION-CONCEPT-G127747) 
(INTERPRETS  POSSIBLE-SITUATION-CONCEPT-G140111) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G848793    CONCEPT-INTERPRETATION 
((INTERPRETS  LOGICAL-PICTURE-BY-WITTGENSTEIN) 
(IS-RELATED-TO-IDEA  SAY-SHOW-DICHOTOMY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G671489    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  POSITIVE-FACT-CONCEPT-G47298) 
(IS-EQUIVALENT-TO  SOA-NOT-THE-CASE-CONCEPT-G65919) 
(IS-SPECIALIZATION-OF  FACT-BY-WITTGENSTEIN) 
(INTERPRETS  NEGATIVE-FACT-CONCEPT-G53480) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G657086    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  NEGATIVE-FACT-CONCEPT-G53480) 
(IS-EQUIVALENT-TO  SOA-THE-CASE-CONCEPT-G59737) 
(IS-SPECIALIZATION-OF  FACT-BY-WITTGENSTEIN) 
(INTERPRETS  POSITIVE-FACT-CONCEPT-G47298) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G642681    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  SOA-THE-CASE-CONCEPT-G59737) 
(IS-EQUIVALENT-TO  NEGATIVE-FACT-CONCEPT-G53480) 
(IS-SPECIALIZATION-OF  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(INTERPRETS  SOA-NOT-THE-CASE-CONCEPT-G65919) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G628278    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  SOA-NOT-THE-CASE-CONCEPT-G65919) 
(IS-EQUIVALENT-TO  POSITIVE-FACT-CONCEPT-G47298) 
(IS-SPECIALIZATION-OF  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(INTERPRETS  SOA-THE-CASE-CONCEPT-G59737) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G613875    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  STRUCTURE-PICTURE-CONCEPT-G72109) 
(INTERPRETS  STRUCTURE-OF-SOA-CONCEPT-G41116) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G599472    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  MATERIAL-PROPERTY-CONCEPT-G28665) 
(HAS-RELATED-CONCEPT  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPERTY-CONCEPT-G34847) 
(INTERPRETS  EXTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G585069    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  EXTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  WORLD-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPERTY-CONCEPT-G34847) 
(INTERPRETS  MATERIAL-PROPERTY-CONCEPT-G28665) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G571193    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  OBJECT-BY-WITTGENSTEIN  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  LOGICAL-FORM-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  PROPERTY-CONCEPT-G34847) 
(INTERPRETS  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G557276    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  OBJECT-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  STATE-OF-AFFAIRS-BY-WITTGENSTEIN   WORLD-BY-WITTGENSTEIN    ) 
(IS-GENERALIZATION-OF  INTERNAL-PROPERTY-BY-WITTGENSTEIN  EXTERNAL-PROPERTY-BY-WITTGENSTEIN  MATERIAL-PROPERTY-CONCEPT-G28665    ) 
(INTERPRETS  PROPERTY-CONCEPT-G34847) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G543427    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  SIMPLE-FACT-CONCEPT-G321374  SIMPLE-S-O-A-CONCEPT-G332662  OBJECT-BY-WITTGENSTEIN ) 
(INTERPRETS  SIMPLE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G529038    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  WORLD-BY-WITTGENSTEIN) 
(INTERPRETS  SUBSTANCE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G442870    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  LOGICAL-FORM-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  OBJECT-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  KNOWING-CONCEPT-G349594) 
(INTERPRETS  KNOWING-AN-OBJECT-CONCEPT-G355238) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G429021    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  THING-BY-WITTGENSTEIN) 
(IS-SPECIALIZATION-OF  ESSENCE-CONCEPT-G470448) 
(INTERPRETS  ESSENCE-OF-THINGS-CONCEPT-G343950) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G415172    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  SUBSTANCE-BY-WITTGENSTEIN  NAME-BY-WITTGENSTEIN   MEANING-NAME-CONCEPT-G161230) 
(REQUIRES-CONCEPT  LOGICAL-FORM-BY-WITTGENSTEIN  PROPERTY-CONCEPT-G34847  LOGICAL-STRUCTURE-CONCEPT-G202215 ) 
(HAS-RELATED-CONCEPT  KNOWING-AN-OBJECT-CONCEPT-G355238   SIMPLE-BY-WITTGENSTEIN     ) 
(HAS-OPPOSITE-CONCEPT  THING-BY-WITTGENSTEIN) 
(IS-EQUIVALENT-TO  ELEMENT-FACT-CONCEPT-G96837      ) 
(IS-GENERALIZATION-OF  LOGICAL-OBJECT-BY-WITTGENSTEIN) 
(INTERPRETS  OBJECT-BY-WITTGENSTEIN) 
))

(def-instance   -CONCEPT-INTERPRETATION-G401303    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  ESSENCE-OF-THINGS-CONCEPT-G343950) 
(HAS-RELATED-CONCEPT  TOTALITY-OF-THINGS-CONCEPT-G304442   SITUATION-CONCEPT-G127747    ) 
(HAS-OPPOSITE-CONCEPT  OBJECT-BY-WITTGENSTEIN) 
(INTERPRETS  THING-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))


(def-instance   -CONCEPT-INTERPRETATION-G131210    CONCEPT-INTERPRETATION 
((IS-EQUIVALENT-TO  TOTALITY-OF-FACTS-CONCEPT-G310086  TOTALITY-OF-TRUE-S-O-A-CONCEPT-G315730) 
(INTERPRETS  WORLD-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G118683    CONCEPT-INTERPRETATION 
((IS-EQUIVALENT-TO  TOTALITY-OF-FACTS-CONCEPT-G310086  WORLD-BY-WITTGENSTEIN) 
(INTERPRETS  TOTALITY-OF-TRUE-S-O-A-CONCEPT-G315730) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G106156    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  TOTALITY-OF-THINGS-CONCEPT-G304442) 
(IS-EQUIVALENT-TO  WORLD-BY-WITTGENSTEIN TOTALITY-OF-TRUE-S-O-A-CONCEPT-G315730) 
(INTERPRETS  TOTALITY-OF-FACTS-CONCEPT-G310086) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G93629    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  THING-BY-WITTGENSTEIN) 
(HAS-OPPOSITE-CONCEPT  TOTALITY-OF-FACTS-CONCEPT-G310086) 
(INTERPRETS  TOTALITY-OF-THINGS-CONCEPT-G304442) 
(CARRIED-OUT-BY  michele-pasin) 
))



(def-instance   -CONCEPT-INTERPRETATION-G197107    CONCEPT-INTERPRETATION 
((IS-EQUIVALENT-TO  SIMPLE-S-O-A-CONCEPT-G332662) 
(IS-SPECIALIZATION-OF  FACT-BY-WITTGENSTEIN) 
(INTERPRETS  SIMPLE-FACT-CONCEPT-G321374) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G171283    CONCEPT-INTERPRETATION 
((IS-EQUIVALENT-TO  COMPLEX-S-O-A-CONCEPT-G332662) 
(IS-SPECIALIZATION-OF  FACT-BY-WITTGENSTEIN) 
(INTERPRETS  COMPLEX-FACT-CONCEPT-G327018) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G158372    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  ELEMENT-FACT-CONCEPT-G96837) 
(HAS-RELATED-CONCEPT  PICTURE-BY-WITTGENSTEIN LOGICAL-FORM-BY-WITTGENSTEIN  SAYING-CONCEPT-G103019  LOGICAL-STRUCTURE-CONCEPT-G202215  TOTALITY-OF-FACTS-CONCEPT-G310086) 
(HAS-OPPOSITE-CONCEPT  SITUATION-CONCEPT-G127747) 
(IS-GENERALIZATION-OF  NEGATIVE-FACT-CONCEPT-G53480 positive-fact-CONCEPT-G47298) 
(INTERPRETS  FACT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G145461    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LOGICAL-SPACE-BY-WITTGENSTEIN) 
(IS-GENERALIZATION-OF  SIMPLE-FACT-CONCEPT-G321374  COMPLEX-FACT-CONCEPT-G327018) 
(INTERPRETS  FACT-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))



(def-instance   -CONCEPT-INTERPRETATION-G361667    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  LOGICAL-POSSIBILITY-CONCEPT-G366629   SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN   ) 
(HAS-RELATED-CONCEPT  FACT-BY-WITTGENSTEIN  STATE-OF-AFFAIRS-BY-WITTGENSTEIN   ) 
(HAS-OPPOSITE-CONCEPT  PROP-NONSENSE-CONCEPT-G223866  PROP-LACK-SENSE-CONCEPT-G216649   SENSE-PICTURE-CONCEPT-G115383    ) 
(IS-GENERALIZATION-OF  PROP-OF-SCIENCE-CONCEPT-G558368) 
(IS-SPECIALIZATION-OF  PROPOSITION-BY-WITTGENSTEIN) 
(INTERPRETS  PROP-WITH-A-SENSE-CONCEPT-G360985) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G347778    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  PROP-WITH-A-SENSE-CONCEPT-G360985) 
(HAS-RELATED-CONCEPT  LOGICAL-SPACE-BY-WITTGENSTEIN) 
(INTERPRETS  LOGICAL-POSSIBILITY-CONCEPT-G366629) 
(CARRIED-OUT-BY  michele-pasin) 
))



(def-instance   -CONCEPT-INTERPRETATION-G276835    CONCEPT-INTERPRETATION 
((CAUSES-CONCEPT  REPRESENTING-RELATION-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  OBJECT-BY-WITTGENSTEIN   PICTURE-BY-WITTGENSTEIN  FACT-BY-WITTGENSTEIN   SHOWING-CONCEPT-G109201  PROPOSITION-BY-WITTGENSTEIN ) 
(IS-EQUIVALENT-TO  INTERNAL-PROPERTY-BY-WITTGENSTEIN) 
(INTERPRETS  LOGICAL-FORM-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G263548    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  LOGICAL-POSSIBILITY-CONCEPT-G366629   FACT-BY-WITTGENSTEIN  LOGICAL-PICTURE-BY-WITTGENSTEIN    ) 
(INTERPRETS  LOGICAL-SPACE-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G250261    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  SIMPLE-S-O-A-CONCEPT-G332662) 
(IS-EQUIVALENT-TO  COMPLEX-FACT-CONCEPT-G327018) 
(IS-SPECIALIZATION-OF  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(INTERPRETS  COMPLEX-S-O-A-CONCEPT-G338306) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G236974    CONCEPT-INTERPRETATION 
((HAS-OPPOSITE-CONCEPT  COMPLEX-S-O-A-CONCEPT-G338306) 
(IS-EQUIVALENT-TO  SIMPLE-FACT-CONCEPT-G321374) 
(IS-SPECIALIZATION-OF  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(INTERPRETS  SIMPLE-S-O-A-CONCEPT-G332662) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G223687    CONCEPT-INTERPRETATION 
((HAS-RELATED-CONCEPT  ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN   INDEPENDENCE-S-O-A-CONCEPT-G322023   ) 
(IS-SPECIALIZATION-OF  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(INTERPRETS  SIMPLE-S-O-A-CONCEPT-G332662) 
(CARRIED-OUT-BY  michele-pasin) 
))

(def-instance   -CONCEPT-INTERPRETATION-G210400    CONCEPT-INTERPRETATION 
((REQUIRES-CONCEPT  OBJECT-BY-WITTGENSTEIN) 
(HAS-RELATED-CONCEPT  EXTERNAL-PROPERTY-BY-WITTGENSTEIN  STRUCTURE-OF-SOA-CONCEPT-G41116 PROPOSITION-BY-WITTGENSTEIN LOGICAL-PICTURE-BY-WITTGENSTEIN   ) 
(IS-EQUIVALENT-TO  POSSIBLE-SITUATION-CONCEPT-G140111) 
(IS-GENERALIZATION-OF  SIMPLE-S-O-A-CONCEPT-G332662  COMPLEX-S-O-A-CONCEPT-G338306  ESSENCE-OF-THINGS-CONCEPT-G343950  TOTALITY-OF-TRUE-S-O-A-CONCEPT-G315730 SOA-NOT-THE-CASE-CONCEPT-G65919   SOA-THE-CASE-CONCEPT-G59737) 
(INTERPRETS  STATE-OF-AFFAIRS-BY-WITTGENSTEIN) 
(CARRIED-OUT-BY  michele-pasin) 
))






;;; +++++++
;;; the original interpretations
;;; +++++++


(def-instance my-interpre-SINNLOS-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SINNLOS-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  WITHOUT-SENSE-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-PROPOSITION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-PROPOSITION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))


(def-instance my-interpre-IDENTITY-SIGN-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets IDENTITY-SIGN-BY-WITTGENSTEIN)
 (is-specialization-of SIGN-BY-WITTGENSTEIN)
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept    )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-EXPRESSION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets EXPRESSION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  SYMBOL-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-A-POSTERIORI-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets A-POSTERIORI-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept A-PRIORI-BY-WITTGENSTEIN)
 (has-related-concept     EXPERIENCE-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-INEXPRESSIBLE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets INEXPRESSIBLE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  INEFFABLE-BY-WITTGENSTEIN  TO-SHOW-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LIFE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LIFE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PERFECT-LANGUAGE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PERFECT-LANGUAGE-BY-WITTGENSTEIN)
 (is-specialization-of LANGUAGE-BY-WITTGENSTEIN)
 (is-generalization-of  )
 (has-opposite-concept ORDINARY-LANGUAGE-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-SPACE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-SPACE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-THING-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets THING-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept OBJECT-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-EXTERNAL-PROPERTY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets EXTERNAL-PROPERTY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept INTERNAL-PROPERTY-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PRIMITIVE-SIGN-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PRIMITIVE-SIGN-BY-WITTGENSTEIN)
 (is-specialization-of SIGN-BY-WITTGENSTEIN)
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-STRUCTURAL-RELATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets STRUCTURAL-RELATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  INTERNAL-RELATION-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-A-PRIORI-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets A-PRIORI-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept A-POSTERIORI-BY-WITTGENSTEIN)
 (has-related-concept     EXPERIENCE-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ROLE-OF-PHILOSOPHY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ROLE-OF-PHILOSOPHY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     PROBLEMS-OF-PHILOSOPHY-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-REPRESENTING-RELATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets REPRESENTING-RELATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-NEGATIVE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets NEGATIVE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ORDINARY-LANGUAGE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ORDINARY-LANGUAGE-BY-WITTGENSTEIN)
 (is-specialization-of LANGUAGE-BY-WITTGENSTEIN)
 (is-generalization-of  )
 (has-opposite-concept PERFECT-LANGUAGE-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-DESCRIBING-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets DESCRIBING-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     NAMING-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-INTERNAL-PROPERTY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets INTERNAL-PROPERTY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept EXTERNAL-PROPERTY-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

#|
(def-instance my-interpre-FORMAL-RELATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FORMAL-RELATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  INTERNAL-RELATION-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))
|#

(def-instance my-interpre-NONSENSICAL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets NONSENSICAL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  UNSINNIG-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-POSITIVE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets POSITIVE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-GOD-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets GOD-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-NAMING-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets NAMING-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     DESCRIBING-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-STRUCTURAL-PROPERTY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets STRUCTURAL-PROPERTY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept EXTERNAL-PROPERTY-BY-WITTGENSTEIN)
 (has-related-concept  INTERNAL-PROPERTY-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-STATE-OF-AFFAIRS-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets STATE-OF-AFFAIRS-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TIME-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TIME-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ANALYSIS-OF-A-PROPOSITION-BY-WITTGENSTEIN concept-interpretation
((carried-out-by michele-pasin)
 (interprets ANALYSIS-OF-A-PROPOSITION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PROPOSITIONAL-SIGN-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROPOSITIONAL-SIGN-BY-WITTGENSTEIN)
 (is-specialization-of SIGN-BY-WITTGENSTEIN)
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PROPOSITIONAL-ATTITUDE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROPOSITIONAL-ATTITUDE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SENSE-OF-THE-PROPOSITION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SENSE-OF-THE-PROPOSITION-BY-WITTGENSTEIN)
 (is-specialization-of SENSE-BY-WITTGENSTEIN)
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     PROPOSITION-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-REALITY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets REALITY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-CONTENT-BY-WITTGESTEIN-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets CONTENT-BY-WITTGESTEIN-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept FORM-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TRUE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TRUE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept FALSE-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FORMAL-PROPERTY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FORMAL-PROPERTY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept EXTERNAL-PROPERTY-BY-WITTGENSTEIN)
 (has-related-concept  INTERNAL-PROPERTY-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TRUTH-OPERATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TRUTH-OPERATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     TRUTH-FUNCTION-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PROJECTION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROJECTION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FORM-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FORM-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept CONTENT-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

#|
(def-instance my-interpre-IDENTITY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets IDENTITY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept DIFFERENCE-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))
|#

(def-instance my-interpre-UNDERSTANDING-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets UNDERSTANDING-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-CLASSIFICATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets CLASSIFICATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-METAPHYSICAL-SUBJECT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept PSYCHOLOGICAL-SUBJECT-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-THOUGHT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets THOUGHT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PSYCHOLOGICAL-SUBJECT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PSYCHOLOGICAL-SUBJECT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept METAPHYSICAL-SUBJECT-BY-WITTGENSTEIN)
 (has-related-concept     SELF-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-CONSTANT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-CONSTANT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  LOGICAL-OBJECT-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-GENERAL-PROPOSITIONAL-FORM-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets GENERAL-PROPOSITIONAL-FORM-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-CONTRADICTION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets CONTRADICTION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept TAUTOLOGY-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SOUL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SOUL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PROBABILITY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROBABILITY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ANALYSIS-OF-A-PROPOSITION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ANALYSIS-OF-A-PROPOSITION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-COMPLEX-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets COMPLEX-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept SIMPLE-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ISOMORPHISM-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ISOMORPHISM-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-VALUE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets VALUE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LAW-OF-CAUSALITY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LAW-OF-CAUSALITY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-VARIABLE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets VARIABLE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-MYSTICAL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets MYSTICAL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-OBJECT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-OBJECT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  LOGICAL-CONSTANT-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-SIGN-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-SIGN-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SIMPLE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SIMPLE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept COMPLEX-BY-WITTGENSTEIN)
 (has-related-concept     ATOMIC-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-NAME-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets NAME-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-CAUSAL-NEXUS-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets CAUSAL-NEXUS-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  INFERENCE-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TO-SHOW-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TO-SHOW-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept TO-SAY-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-NEGATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets NEGATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept AFFIRMATION-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TRUTH-FUNCTION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TRUTH-FUNCTION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     TRUTH-OPERATION-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-FORM-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-FORM-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FACT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FACT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-EXPERIENCE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets EXPERIENCE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SELF-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SELF-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     PSYCHOLOGICAL-SUBJECT-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-NATURAL-SCIENCE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets NATURAL-SCIENCE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-WILL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets WILL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PROBLEMS-OF-PHILOSOPHY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROBLEMS-OF-PHILOSOPHY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     ROLE-OF-PHILOSOPHY-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TO-SAY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TO-SAY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept TO-SHOW-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-COMPLEX-PROPOSITION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets COMPLEX-PROPOSITION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SYMBOL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SYMBOL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  EXPRESSION-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-AFFIRMATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets AFFIRMATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept NEGATION-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SPACE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SPACE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-PICTURE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-PICTURE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

#|
(def-instance my-interpre-DIFFERENCE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets DIFFERENCE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept IDENTITY-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))
|#

(def-instance my-interpre-PROPOSITIONAL-VARIABLE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROPOSITIONAL-VARIABLE-BY-WITTGENSTEIN)
 (is-specialization-of VARIABLE-BY-WITTGENSTEIN)
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-INTERNAL-RELATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets INTERNAL-RELATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ESSENCE-OF-THE-WORLD-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ESSENCE-OF-THE-WORLD-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     WORLD-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TRUTH-GROUNDS-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TRUTH-GROUNDS-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PICTURE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PICTURE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )
 (IS-RELATED-TO-IDEA  NOTES-METAPHOR-G385433  ) ))

(def-instance my-interpre-SUBSTANCE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SUBSTANCE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ELEMENTARY-PROPOSITION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ELEMENTARY-PROPOSITION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept COMPLEX-PROPOSITION-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SIGN-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SIGN-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-INEFFABLE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets INEFFABLE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  INEXPRESSIBLE-BY-WITTGENSTEIN  TO-SHOW-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-WORLD-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets WORLD-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  WILL-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-INFERENCE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets INFERENCE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  CAUSAL-NEXUS-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FORMAL-CONCEPT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FORMAL-CONCEPT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-MEANING-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets MEANING-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ACCIDENTAL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ACCIDENTAL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept ESSENTIAL-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FORM-OF-REPRESENTATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FORM-OF-REPRESENTATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-AAAAA-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets AAAAA-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-DEATH-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets DEATH-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LAW-OF-NATURE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LAW-OF-NATURE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FREE-WILL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FREE-WILL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LINGUISTIC-ABILITY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LINGUISTIC-ABILITY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LAW-OF-INDUCTION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LAW-OF-INDUCTION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SIGN-SYMBOL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SIGN-SYMBOL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-WITHOUT-SENSE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets WITHOUT-SENSE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  SINNLOS-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LOGICAL-INDEPENDENCE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LOGICAL-INDEPENDENCE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ESSENTIAL-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ESSENTIAL-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept ACCIDENTAL-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FUNCTION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FUNCTION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-FALSE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets FALSE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept TRUE-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-OBJECT-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets OBJECT-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  THING-BY-WITTGENSTEIN )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-SENSE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets SENSE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-ROLE-OF-LOGIC-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets ROLE-OF-LOGIC-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (IS-RELATED-TO-IDEA  SCAFFOLDING-METAPHOR-G383571)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TAUTOLOGY-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TAUTOLOGY-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (IS-RELATED-TO-IDEA  SCAFFOLDING-METAPHOR-G383571)
 (has-opposite-concept CONTRADICTION-BY-WITTGENSTEIN)
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-UNSINNIG-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets UNSINNIG-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept  NONSENSICAL-BY-WITTGENSTEIN   )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-TRUTH-POSSIBILITIES-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets TRUTH-POSSIBILITIES-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-STRUCTURE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets STRUCTURE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept     FORM-BY-WITTGENSTEIN)
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LIMIT-OF-LANGUAGE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LIMIT-OF-LANGUAGE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-LANGUAGE-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets LANGUAGE-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PROPOSITION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROPOSITION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))

(def-instance my-interpre-PROJECTIVE-RELATION-by-wittgenstein concept-interpretation
((carried-out-by michele-pasin)
 (interprets PROJECTIVE-RELATION-BY-WITTGENSTEIN)
 (is-specialization-of  )
 (is-generalization-of  )
 (has-opposite-concept  )
 (has-related-concept      )
 (requires-concept  )
 (causes-concept  )))